const url = window.location.href;

const searchParams = new URL(url).searchParams;

const entries = new URLSearchParams(searchParams).entries();

const entriesArray = Array.from(entries);

const realEntriesArray = entriesArray[0];

const query = realEntriesArray[1].toLowerCase().replaceAll(/\s/g, "");

const keys = [
    "google", "https://www.google.com",
    "g", "https://www.google.com",
    "goog", "https://www.google.com",
    "bing", "https://www.bing.com",
    "yandex", "https://www.yandex.com",
    "duckduckgo", "https://www.duckduckgo.com",
    "duck", "https://www.duckduckgo.com",
    "ask", "https://www.ask.com",
    "askjeeves", "https://www.ask.com",
    "jeeves", "https://www.ask.com",
    "yahoo", "https://www.yahoo.com",
    "bravesearch", "https://search.brave.com",
    "brave", "https://www.brave.com",
    "ecosia", "https://www.ecosia.org",
    "searx", "https://searxng.canine.tools",
    "searxng", "https://searxng.canine.tools",
    "startpage", "https://www.startpage.com",
    "wiby", "https://www.wiby.me",
    "metager", "https://www.metager.org",
    "swisscows", "https://www.swisscows.com",
    "mojeek", "https://www.mojeek.com",
    "kagi", "https://www.kagi.com",
    "googlesearch", "https://www.google.com",
    "gsearch", "https://www.google.com",
    "googsearch", "https://www.google.com",
    "bingsearch", "https://www.bing.com",
    "yandexsearch", "https://www.yandex.com",
    "duckduckgosearch", "https://www.duckduckgo.com",
    "ducksearch", "https://www.duckduckgo.com",
    "asksearch", "https://www.ask.com",
    "askjeevessearch", "https://www.ask.com",
    "jeevessearch", "https://www.ask.com",
    "yahoosearch", "https://www.yahoo.com",
    "bravebrowser", "https://www.brave.com",
    "ecosiasearch", "https://www.ecosia.org",
    "searxsearch", "https://searxng.canine.tools",
    "searxngsearch", "https://searxng.canine.tools",
    "startpagesearch", "https://www.startpage.com",
    "wibysearch", "https://www.wiby.me",
    "metagersearch", "https://www.metager.org",
    "swisscowssearch", "https://www.swisscows.com",
    "mojeeksearch", "https://www.mojeek.com",
    "kagisearch", "https://www.kagi.com",
    "baidusearch", "https://www.baidu.com",
    "perplexity", "https://www.perplexity.ai",
    "perplexityai", "https://www.perplexity.ai",
    "chatgpt", "https://www.chatgpt.com",
    "chatgptai", "https://www.chatgpt.com",
    "mistral", "https://chat.mistral.ai",
    "mistralai", "https://chat.mistral.ai",
    "stral", "https://chat.mistral.ai",
    "claude", "https://www.claude.ai",
    "claudeai", "https://www.claude.ai",
    "anthropic", "https://www.claude.ai",
    "anthropicclaude", "https://www.claude.ai",
    "anthropicai", "https://www.claude.ai",
    "claudeopus", "https://www.claude.ai",
    "claudeopusai", "https://www.claude.ai",
    "claudefable", "https://www.claude.ai",
    "claudefableai", "https://www.claude.ai",
    "claudesonnet", "https://www.claude.ai",
    "claudesonnetai", "https://www.claude.ai",
    "claudehaiku", "https://www.claude.ai",
    "claudehaikuai", "https://www.claude.ai",
    "deepseek", "https://www.deepseek.com",
    "deepseekai", "https://www.deepseek.com",
    "gemini", "https://gemini.google.com",
    "geminiai", "https://gemini.google.com",
    "googlegeminiai", "https://gemini.google.com",
    "googlegemini", "https://gemini.google.com",
    "geminiflash", "https://gemini.google.com",
    "geminiflashai", "https://gemini.google.com",
    "googlegeminiflash", "https://gemini.google.com",
    "googlegeminiflashai", "https://gemini.google.com",
    "geminipro", "https://gemini.google.com",
    "geminiproai", "https://gemini.google.com",
    "googlegeminipro", "https://gemini.google.com",
    "googlegeminiproai", "https://gemini.google.com",
    "kimi", "https://www.kimi.ai",
    "kimiai", "https://www.kimi.ai",
    "moonshotkimiai", "https://www.kimi.ai",
    "moonshotkimi", "https://www.kimi.ai",
    "moonshot", "https://www.kimi.ai",
    "moonshotai", "https://www.kimi.ai",
    "grok", "https://www.grok.com",
    "grokai", "https://www.grok.com",
    "qwen", "https://www.qwen.com",
    "qwenai", "https://www.qwen.com",
    "alibabaqwen", "https://www.qwen.com",
    "alibabaqwenai", "https://www.qwen.com",
    "copilot", "https://www.copilot.com",
    "copilotai", "https://www.copilot.com",,
    "microsoftcopilot", "https://www.copilot.com",
    "microsoftcopilotai", "https://www.copilot.com",
    "mscopilot", "https://www.copilot.com",
    "mscopilotai", "https://www.copilot.com",
    "gmail", "https://www.gmail.com",
    "googlemail", "https://www.gmail.com",
    "googmail", "https://www.gmail.com",
    "googleemail", "https://www.gmail.com",
    "outlook", "https://www.outlook.com",
    "microsoftoutlook", "https://www.outlook.com",
    "msoutlook", "https://www.outlook.com",
    "outlookemail", "https://www.outlook.com",
    "outlookmail", "https://www.outlook.com",
    "msoutlookmail", "https://www.outlook.com",
    "msoutlookemail", "https://www.outlook.com",
    "microsoftoutlookmail", "https://www.outlook.com",
    "microsoftoutlookemail", "https://www.outlook.com",
    "hotmail", "https://www.outlook.com",
    "hotmailemail", "https://www.outlook.com",
    "yahoomail", "https://mail.yahoo.com",
    "yahooemail", "https://mail.yahoo.com",
    "protonmail", "https://mail.proton.me",
    "protonemail", "https://mail.proton.me",
    "swisscowsemail", "https://swisscows.email",
    "pairmail", "https://webmail.pair.com",
    "pairemail", "https://webmail.pair.com",
    "pairwebmail", "https://webmail.pair.com"
];

const locks = keys.indexOf(query) + 1;

console.log(locks);

if (locks === 0){
    window.location.href = "https://search.brave.com/search?q=" + realEntriesArray[1];
} else {
    window.location.href = keys[locks];
}